name: Build Cosmopolitan Binaries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          
      - name: Build with Cosmopolitan
        run: |
          nix-shell support/shell.nix --run "./support/build-with-cosmo.sh"
          
      - name: Test the binary
        run: |
          ./cosmo-bin/minicoder.com --help
          
      - name: Package binaries
        run: |
          cd cosmo-bin
          tar -czf ../minicoder-cosmo-${{ github.ref_name }}.tar.gz *
          cd ..
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cosmopolitan-binaries
          path: cosmo-bin/*
          
